#!/bin/sh

for file; do

	if [ -f "$file" ] ; then


                DATE=`date -r "$file" +%s`
		ODATE=`getfattr --only-values -n user.htag.ts "$file" 2>/dev/null`
		if [ "0$DATE" -ne "0$ODATE" ]; then
			HTAG=`getfattr --only-values -n user.htag.sha256 "$file" 2>/dev/null` 
			if [ -z "$HTAG" ]; then
				HTAG="<unknown>"
			fi
		else
			HTAG="<outdated>"
		fi
		echo -n "$file"
		echo -ne "\t"
		echo "$HTAG"

		
	fi

done
