#!/bin/bash

htag() {
	file="$1"
	if [ -f "$file" ] ; then

                DATE=`date -r "$file" +%s`
		ODATE=`getfattr --only-values -n user.htag.ts "$file" 2>/dev/null`
		HTAG=`getfattr --only-values -n user.htag.sha256 "$file" 2>/dev/null` 
		if [ "0$DATE" -ne "0$ODATE" ]; then
			if [ -z "$HTAG" ]; then
				HTAG="<unknown>"
			else
				HTAG="<outdated>"
			fi
		fi

		echo -n "$HTAG  "
		echo "$file"

		
	fi
}

if [ $# -eq 0 ]; then
	for file in *; do htag "$file"; done
else
	for file in "$@"; do htag "$file"; done
fi
