#!/bin/sh

force=0
while getopts "f" flag; do
	force=1
done

if [ $# -eq 0 ]; then
	echo "Usage: mkhtag [-f] FILE..." >&2
	echo "  Update htag checksums for the given file(s)" >&2
	echo "  -f	force checksum update (ignore timestamp)" >&2
	exit 1;
fi

for file
do
	if [ -f "$file" ] ; then
		DATE=`date -r "$file" +%s`
		ODATE=`getfattr --only-values -n user.htag.ts "$file" 2>/dev/null`

		if [ "$DATE" = "$ODATE" ] && [ "0" -eq "$force" ]; then
			echo "mkhtag: $file: checksum up to date" >&2
		else
			echo -n "mkhtag: $file: updating... " >&2
			CKSUM=`sha256sum "$file" |awk '{print $1}'`
			echo "$CKSUM" >&2
			setfattr -n user.htag.ts -v "$DATE" "$file"
			setfattr -n user.htag.sha256 -v "$CKSUM" "$file"
		fi

	fi
done
