#!/bin/bash
# shatag, Copyright 2010 Maxime Augier
# Distributed under the terms of the GNU General Public License (GPL)

force=0
verbose=0

while getopts "fv" flag; do case "$flag" in
	f) force=1 ;;
	v) verbose=1 ;;
	[?]) usage ;;
esac; done

ifverbose() { if [ $verbose -ne 0 ]; then "$@"; fi }

usage() {
	echo "Usage: mkhtag [-fv] FILE..." >&2
	echo "  Update htag checksums for the given file(s)" >&2
	echo "  -f	force checksum update (ignore timestamp)" >&2
	echo "  -v	verbose" >&2
	exit 1;
}

if [ $# -eq 0 ]; then usage; fi

for file
do
	if [ -f "$file" ] ; then
		DATE=`date -r "$file" +%s`
		ODATE=`getfattr --only-values -n user.htag.ts "$file" 2>/dev/null`

		if [ "0$DATE" -eq "0$ODATE" ] && [ "0" -eq "$force" ]; then
			ifverbose echo "mkhtag: $file: checksum up to date" >&2
		else
			CKSUM=`sha256sum "$file" |awk '{print $1}'`
			echo "$CKSUM  $file"
			setfattr -n user.htag.sha256 -v "$CKSUM" "$file"
			setfattr -n user.htag.ts -v "$DATE" "$file"
		fi

	fi
done
